version: 2
jobs:
  build:
    docker:
      - image: 834914689975.dkr.ecr.eu-west-1.amazonaws.com/builder:latest
        aws_auth:
          aws_access_key_id: $KITMAN_IMAGES_AWS_ACCESS_KEY_ID
          aws_secret_access_key: $KITMAN_IMAGES_AWS_SECRET_KEY

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Test
          command: |
            echo "test"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context: build-deploy
