version: 2

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context: build-deploy

jobs:
  build:
    docker:
      - image: 834914689975.dkr.ecr.eu-west-1.amazonaws.com/builder:latest
        aws_auth:
          aws_access_key_id: $KITMAN_IMAGES_AWS_ACCESS_KEY_ID
          aws_secret_access_key: $KITMAN_IMAGES_AWS_SECRET_KEY

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install tfenv and tgenv
          command: |
            git clone --depth=1 https://github.com/tfutils/tfenv.git $HOME/.tfenv
            git clone https://github.com/cunymatthieu/tgenv.git $HOME/.tgenv

      - run:
          name: Terragrunt Plan - Forcing Path
          command: |
            PATH="$HOME/.tfenv/bin:$HOME/.tgenv/bin:$PATH"
            cd global/organizations/sandbox/eu-west-1/null-resource
            tgenv install $(.terragrunt-version) && tgenv use $(.terragrunt-version)
            terragrunt plan
