version: 2

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - plan:
          context: build-deploy
      - hold:
          type: approval
          requires:
            - plan
      - apply:
          context: build-deploy
          requires:
            - hold

jobs:
  plan:
    docker:
      - image: 834914689975.dkr.ecr.eu-west-1.amazonaws.com/builder:latest
        aws_auth:
          aws_access_key_id: $KITMAN_IMAGES_AWS_ACCESS_KEY_ID
          aws_secret_access_key: $KITMAN_IMAGES_AWS_SECRET_KEY

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install tfenv and tgenv
          command: |
            git clone --depth=1 https://github.com/tfutils/tfenv.git $HOME/.tfenv
            git clone https://github.com/cunymatthieu/tgenv.git $HOME/.tgenv

      - run:
          name: Terragrunt Plan - Forcing Path
          command: ./.circleci/plan.sh

      - run:
          name: Post Plan to GitHub PR
          command: |
            set -x
            cd global/organizations/sandbox/eu-west-1/null-resource

            pr_response=$(curl --location --request GET "https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pulls?head=$CIRCLE_PROJECT_USERNAME:$CIRCLE_BRANCH&state=open" \
            -u $GH_USER:$GH_TOKEN)

            if [ $(echo $pr_response | jq length) -eq 0 ]; then
              echo "No PR found to update"
            else
              pr_comment_url=$(echo $pr_response | jq -r ".[]._links.comments.href")
            fi

            PLAN_TXT=$(cat plan.txt | jq -sR .)

            DATA_RAW="<details>\n<summary>Terragrunt Plan - $(pwd)</summary>\n\n\`\`\`sh\n${PLAN_TXT:1:-1}\`\`\` \n</details>"

            curl --request POST "$pr_comment_url" \
              --location \
              -u $GH_USER:$GH_TOKEN \
              --header 'Content-Type: application/json' \
              --data-raw "{
                \"body\": \"$DATA_RAW\"
              }"

      - persist_to_workspace:
          root: .
          paths:
            - global

  apply:
    docker:
      - image: 834914689975.dkr.ecr.eu-west-1.amazonaws.com/builder:latest
        aws_auth:
          aws_access_key_id: $KITMAN_IMAGES_AWS_ACCESS_KEY_ID
          aws_secret_access_key: $KITMAN_IMAGES_AWS_SECRET_KEY

    working_directory: ~/repo

    steps:
      - attach_workspace:
          at: /workspace

      - checkout

      - run:
          name: Install tfenv and tgenv
          command: |
            git clone --depth=1 https://github.com/tfutils/tfenv.git $HOME/.tfenv
            git clone https://github.com/cunymatthieu/tgenv.git $HOME/.tgenv

      - run:
          name: Apply TF Plan
          command: pwd && ls -la && cd ~/repo && ./.circleci/apply.sh

      - run:
          name: Post Apply to GitHub PR
          command: |
            set -x
            cd /workspace/global/organizations/sandbox/eu-west-1/null-resource
            pr_response=$(curl --location --request GET "https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pulls?head=$CIRCLE_PROJECT_USERNAME:$CIRCLE_BRANCH&state=open" \
            -u $GH_USER:$GH_TOKEN)

            if [ $(echo $pr_response | jq length) -eq 0 ]; then
              echo "No PR found to update"
            else
              pr_comment_url=$(echo $pr_response | jq -r ".[]._links.comments.href")
            fi

            APPLY_TXT=$(cat apply.txt | jq -sR .)
            DATA_RAW="<details>\n<summary>Terragrunt Apply - $(pwd)</summary>\n\n\`\`\`sh\n${APPLY_TXT:1:-1}\`\`\` \n</details>"
            curl --request POST "$pr_comment_url" \
              --location \
              -u $GH_USER:$GH_TOKEN \
              --header 'Content-Type: application/json' \
              --data-raw "{
                \"body\": \"$DATA_RAW\"
              }"
